### ISSUE TITLE
rotate workplace command

### ISSUE THREAD

**Issue by Corallus-Caninus** [SimulaVR/Simula#129]
This software is awesome! I need to rotate the entire workspace every ~30 minutes due to accelerometer drift, is there any way to "rotate all windows" to offset this effect? 

If the source was available I'd attempt a patch myself but it seems to be walled off by nix/cachix. 

This software is too important for people who don't have a lot. I am getting 4k like experience with an old android phone and laptop. I really want to help share this with people/the world.

**Comment by KaneTW** [comment]
You should be able to modify it and then just build with nix as usual. Nix
is fully transparent, it just speeds up deployment with cachix. The
relevant code is in addons/godot-haskell-plugin

Anyway, we'll put it on the list.

**Comment by Corallus-Caninus** [comment]
Thank you I misunderstood the project's directory structure.

**Comment by georgewsinger** [comment]
@Corallus-Caninus See https://github.com/SimulaVR/Simula/commit/b1976bbaad49a5880010bbf8d993e1521eac1908 (`dev` branch) for a DRAFT implementation.  There are a few limitations of this implementation right now, which will be fixed in the next commit(s):

- Rotating the windows also rotates the skybox, which I think is undesired.  There are a few different ways to fix this, but basically we'll have to adjust the scene graph hierarchy.
- The first few frames of rotation sometimes (but not always) seem to jitter the windows a tad, before it stabilizes.  This is at least what happens on my setup.  I'm curious if it happens on your setup?

Right now the key is binded to `Super + m` (the one I was user for testing).  Let me know if you think there's a better default keybind for this.

**Comment by georgewsinger** [comment]
The skybox dragging issue should now be fixed in https://github.com/SimulaVR/Simula/commit/17ff399c5e4d1e3f315becc0b4516d3fedee5bd8.

**Comment by georgewsinger** [comment]
From Simula Discord:

> Okay I seem to have some bugs with the new feature so I'm holding off on closing the issue until we can solve them.
> 
> 1. when moving windows after rotating workspace my gaze control (super + alt) is stuck on the previous position.
> 
> 2. after moving windows with super+m a repeat of super+m resets my perspective to the perspective before the rotation.

These issues should be fixed in https://github.com/SimulaVR/Simula/commit/2c06e7454b6529dcf20d78433272aef56fa200f8 I'll wait to close though this is more battle tested.

**Comment by Corallus-Caninus** [comment]
Solved with 2c06e7454b6529dcf20d78433272aef56fa200f8
